### ISSUE TITLE
Project is not working

### ISSUE THREAD

**Issue by ishroid** [dheeraj-bhadoria/Compose-Login-Screen-for-Android-iOS-and-Desktop-Common-UI#1]
could you please let me know what could be the issue here, i am always getting this error

The following build commands failed:
	PhaseScriptExecution [CP-User]\ Build\ common/user/Compose-Login-Screen-for-Android-iOS-and-Desktop-Common-UI-master/build/ios/Pods.build/Debug-iphonesimulator/common.build/Script-7117138631DE463A2F0FAF7227B3ADA6.sh (in target 'common' from project 'Pods')
(1 failure)

**Comment by dheeraj-bhadoria** [comment]
@ishroid Are you running app in Mac or Windows?

**Comment by ishroid** [comment]
I am using MAC

**Comment by dheeraj-bhadoria** [comment]
Can you please follow all the following steps before running app- 

Set up the environment

    Warning You need a Mac with macOS to write and run iOS-specific code on simulated or real devices. This is an Apple requirement.

To work with this template, you need the following:

    A machine running a recent version of macOS
    [Xcode](https://apps.apple.com/us/app/xcode/id497799835)
    [Android Studio](https://developer.android.com/studio)
    The [Kotlin Multiplatform Mobile plugin](https://plugins.jetbrains.com/plugin/14936-kotlin-multiplatform-mobile)
    The [CocoaPods dependency manager](https://kotlinlang.org/docs/native-cocoapods.html)

Check your environment

Before you start, use the [KDoctor](https://github.com/Kotlin/kdoctor) tool to ensure that your development environment is configured correctly:

    Install KDoctor with [Homebrew](https://brew.sh/):

    brew install kdoctor

    Run KDoctor in your terminal:

    kdoctor

    If everything is set up correctly, you'll see valid output:

    Environment diagnose (to see all details, use -v option):
    [✓] Operation System
    [✓] Java
    [✓] Android Studio
    [✓] Xcode
    [✓] Cocoapods

    Conclusion:
      ✓ Your system is ready for Kotlin Multiplatform Mobile development!

Otherwise, KDoctor will highlight which parts of your setup still need to be configured and will suggest a way to fix them.

**Comment by dheeraj-bhadoria** [comment]
No update on previous comment. So going to close this.
